{
 "title": "Apidays Mad 19",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Books Sold - Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum (books_sold{app=\"go-prometheus-demo\"}))"
    }
   ]
  },
  {
   "title": "Online Users",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(online_users{app=\"go-prometheus-demo\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Books Sold - Terror genre",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum (books_sold{genre=\"terror\",app=\"go-prometheus-demo\"}))"
    }
   ]
  },
  {
   "title": "Books Sold - Romance genre",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum (books_sold{genre=\"romance\"}))"
    }
   ]
  },
  {
   "title": "Books Sold - Child genre",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum (books_sold{genre=\"scifi\",app=\"go-prometheus-demo\"}))"
    }
   ]
  },
  {
   "title": "Sells by genre",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (genre) (rate(books_sold{app=\"go-prometheus-demo\"}[5m]))",
     "legendFormat": "{{ genre }}"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum by (code) (rate(requests_total[5m])))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Pages heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(books_sold_pages_bucket{le!=\"+Inf\"}[15m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests by Method",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum by (method) (rate(requests_total{}[5m])))",
     "legendFormat": "{{ method }}"
    }
   ]
  }
 ]
}