apiVersion: v1
kind: Service
metadata:
  name: go-prometheus-demo
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: go-prometheus-demo
  sessionAffinity: None
  type: LoadBalancer
